spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/renegdb
    username: reneg
    password: reneg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:data-docker.sql
  h2:
    console:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
